app:
  name: kapowarr
  image: "mrcas/kapowarr:latest"
  replicas: 1
  servicePort: 5656
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  httpRoutePath: "/kapowarr"
  volumeMounts:
    - name: config
      mountPath: /app/db
      subPath: kapowarr
    - name: media
      mountPath: /app/temp_downloads
      subPath: downloads
    - name: media
      mountPath: /comics
      subPath: media/books/comics
  env:
    PUID: "1000"
    PGID: "1000"
