app:
  name: kapowarr
  image: "mrcas/kapowarr:latest"
  servicePort: 5656
  gateway:
    enabled: true
    httpRoutePath: "/kapowarr"
  volumeMounts:
    - name: config
      mountPath: /app/db
      subPath: kapowarr
    - name: media
      mountPath: /app/temp_downloads
      subPath: downloads
    - name: media
      mountPath: /comics
      subPath: media/books/comics
  environmentData:
    env:
      PUID: "1000"
      PGID: "1000"
