app:
  name: sabnzbd
  image: "lscr.io/linuxserver/sabnzbd:latest"
  replicas: 1
  servicePort: 8080
  gateway:
    enabled: true
    httpRoutePath: "/"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: sabnzbd
    - name: media
      mountPath: /downloads
      subPath: downloads/sabnzbd
  env:
    PUID: "1000"
    PGID: "1000"
    TZ: "Etc/UTC"
  hostnames:
    - sabnzbd.local
