app:
  name: sabnzbd
  image: "lscr.io/linuxserver/sabnzbd:latest"
  replicas: 1

  pod:
    ports:
      servicePort: 8080

  gateway:
    enabled: true
    httpRoutePath: "/"
    hostnames:
      - sabnzbd.local
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: sabnzbd
    - name: media
      mountPath: /downloads
      subPath: downloads/sabnzbd
  environmentData:
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
