app:
  name: jellyfin
  image: "jellyfin/jellyfin:latest"
  servicePort: 8096
  gateway:
    enabled: true
    httpRoutePath: "/jellyfin"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: jellyfin
    - name: media
      mountPath: /data
      subPath: media
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
