app:
  name: jellyfin

  pod:
    image: "jellyfin/jellyfin:latest"
    ports:
      servicePort: 8096
    volumeMounts:
      - name: config
        mountPath: /config
        subPath: jellyfin
      - name: media
        mountPath: /data
        subPath: media
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  gateway:
    enabled: true
    httpRoutePath: "/jellyfin"
