app:
  name: bazarr
  replicas: 1

  pod:
    image: "lscr.io/linuxserver/bazarr:latest"
    ports:
      servicePort: 6767
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1024Mi
    volumeMounts:
      - name: config
        mountPath: /config
        subPath: bazarr
      - name: media
        mountPath: /downloads
        subPath: downloads
      - name: media
        mountPath: /media/tvshows
        subPath: media/tvshows
      - name: media
        mountPath: /media/movies
        subPath: media/movies
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  gateway:
    enabled: true
    httpRoutePath: "/bazarr"
