apiVersion: v2
name: mylar3
description: A Helm chart for Mylar3

# A chart can be either an 'application' or a 'library' chart. A library chart
# is a collection of templates that can be re-used in other charts.
type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
  - name: basechart
    version: "0.1.0"
    repository: "file://../basechart"
    alias: app
