apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.service.name }}-http-route
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: kube-system
  # NOTE: If no hostnames are given, this will match them all. For a local
  # setup it's perfect.
  hostnames:
    {{- toYaml .Values.hostnames | nindent 4 }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      # filters:
      #   # STRIP THE PREFIX: Send '/qb/login.html' to the pod as '/login.html'
      #   - type: URLRewrite
      #     urlRewrite:
      #       path:
      #         type: ReplacePrefixMatch
      #         replacePrefixMatch: /
        # # SECURITY FIX: qBittorrent rejects requests if the 'Host' header is 'wrong'
        # - type: RequestHeaderModifier
        #   requestHeaderModifier:
        #     set:
        #       - name: X-Forwarded-Host
        #         value: "localhost"
      backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.service.servicePort }}
