app:
  name: readarr
  replicas: 1

  pod:
    image: "linuxserver/readarr:0.4.19-nightly"
    ports:
      servicePort: 8787
    volumeMounts:
      - name: config
        mountPath: /config
        subPath: readarr
      - name: media
        mountPath: /downloads
        subPath: downloads
      - name: media
        mountPath: /media/books
        subPath: media/books
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  gateway:
    enabled: true
    httpRoutePath: "/readarr"
