app:
  name: readarr
  image: "linuxserver/readarr:0.4.19-nightly"
  replicas: 1

  pod:
    ports:
      servicePort: 8787

  gateway:
    enabled: true
    httpRoutePath: "/readarr"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: readarr
    - name: media
      mountPath: /downloads
      subPath: downloads
    - name: media
      mountPath: /media/books
      subPath: media/books
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
