# This chart is intended to manage a single deployment, which is almost
# always the case for media stack apps. If you need to manage multiple
# deployments, you can create multiple instances of this chart with different
# aliases

name: ""
replicas: 1

pod:
  image: ""
  ports:
    servicePort: 25600
    extraPorts: []
      # - name: amule-tcp
      #   port: 4662
      #   protocol: TCP
      # - name: amule-udp
      #   port: 4665
      #   protocol: UDP
      # - name: extended-udp
      #   port: 4672
      #   protocol: UDP
    hostPorts: []
      # - name: "amule-tcp"
      #   port: 4662
      #   protocol: TCP

  annotations: {}

  podOptions: {}

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits: {}
    #   cpu: 1
    #   memory: 1024Mi

  probes:
    livenessProbe: {}
      # httpGet:
      #   path: /komga/actuator/health
      #   port: 25600
      # initialDelaySeconds: 30
      # periodSeconds: 10
      # failureThreshold: 1
    readinessProbe: {}
      # httpGet:
      #   path: /komga/actuator/health
      #   port: 25600
      # initialDelaySeconds: 30
      # periodSeconds: 5

  volumeMounts: []
    # - name: config
    #   mountPath: /config
    #   subPath: komga
    # - name: media
    #   mountPath: /data
    #   subPath: media/books

  environmentData:
    env: {}
    envSecrets: []
      # - name: ENV_VAR_NAME
      #   secretName: secret-name
      #   key: secret-key
    # Optional name of a Kubernetes Secret containing environment variables to be
    # injected into the container. The Secret should be in the same
    # namespace as the Deployment and should have key-value pairs where
    # the key is the name of the environment variable and the value is the
    # value of the environment variable.
    envSecretName: ""

  securityContext: {}
    # runAsUser: 1000
    # runAsGroup: 1000
    # fsGroup: 1000

gateway:
  enabled: true
  secure: false
  hostnames: []
  # e.g. "/komga" - only needed if you want to serve the app on
  # a subpath of your domain (e.g. example.com/komga). If empty,
  # it will be served on the root of the domain (e.g. komga.example.com)
  httpRoutePath: ""

exposeService: true

storage:
  # Load these claims into the chart to be used as volume mounts. The chart will not
  # create these claims.
  fromClaims:
    - name: "config"
      claimName: "config-pvc"
    - name: "media"
      claimName: "media-pvc"
  extraVolumes: []
    # - name: homepage-config
    #   configMap:
    #     name: homepage-config
    # - name: logs
    #   emptyDir: {}
