app:
  name: amule
  replicas: 1

  pod:
    image: "ngosang/amule:latest"

    ports:
      servicePort: 4711
      extraPorts:
        - name: amule-tcp
          port: 4662
          protocol: TCP
        - name: amule-udp
          port: 4665
          protocol: UDP
        - name: extended-udp
          port: 4672
          protocol: UDP

    volumeMounts:
      - name: config
        mountPath: /home/amule/.aMule
        subPath: amule
      - name: media
        mountPath: /incoming
        subPath: downloads/amule
      - name: media
        mountPath: /temp
        subPath: downloads/amule/temp

    environmentData:
      env:
        MOD_AUTO_RESTART_ENABLED: "true"
        MOD_AUTO_RESTART_CRON: "0 6 * * *"
        MOD_AUTO_SHARE_ENABLED: "false"
        MOD_AUTO_SHARE_DIRECTORIES: "/incoming"
        MOD_FIX_KAD_GRAPH_ENABLED: "true"
        MOD_FIX_KAD_BOOTSTRAP_ENABLED: "true"
        GUI_PWD: "mypass"
        WEBUI_PWD: "mypass"
        TZ: "Europe/Madrid"
        PUID: "1000"
        PGID: "1000"

  gateway:
    enabled: true
    httpRoutePath: "/"
    hostnames:
      - amule.local
