apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      volumes:
        - name: {{ .Values.service.name }}-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Values.service.name }}-pv-claim
      # securityContext:
      #   runAsUser: 1000
      #   runAsGroup: 1000
      #   fsGroup: 1000
      containers:
        - image: {{ .Values.service.image }}
          name: {{ .Values.service.name }}
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.service.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.service.readinessProbe | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.servicePort }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.service.name }}-pv-storage
              mountPath: /config
              subPath: config
            - name: {{ .Values.service.name }}-pv-storage
              mountPath: /data
              subPath: data
          envFrom:
            - configMapRef:
                name: {{ .Values.service.name }}-config
