apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.name }}-pv-claim
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
