service:
  name: flaresolverr
  image: "ghcr.io/flaresolverr/flaresolverr:latest"
  replicas: 1
  servicePort: 8191
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1024Mi
  livenessProbe:
  readinessProbe:
  httpRoutePath: "/"
  volumeMounts:
  env:

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

hostnames: []

storage:
  configClaimName: config-pvc
  mediaClaimName: media-pvc

gatewayClassName: traefik
