app:
  name: flaresolverr
  image: "ghcr.io/flaresolverr/flaresolverr:latest"
  replicas: 1

  pod:
    ports:
      servicePort: 8191

  gateway:
    enabled: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
