app:
  name: flaresolverr
  replicas: 1

  pod:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    ports:
      servicePort: 8191
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  gateway:
    enabled: false
