app:
  name: metube
  replicas: 1

  pod:
    image: "ghcr.io/alexta69/metube"
    ports:
      servicePort: 8081
    volumeMounts:
      - name: media
        mountPath: /downloads
        subPath: media/youtube
    environmentData:
      env:
        URL_PREFIX: "/metube"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  gateway:
    enabled: true
    httpRoutePath: "/metube"
