service:
  name: paperless-ngx
  image: "ghcr.io/paperless-ngx/paperless-ngx:latest"
  replicas: 1
  servicePort: 8000
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      #cpu: 1
      #memory: 1024Mi
  livenessProbe:
  readinessProbe:
  httpRoutePath: "/paperless"
  volumeMounts:
    - name: config
      mountPath: /usr/src/paperless/data
      subPath: paperless-ngx/data
    - name: media
      mountPath: /usr/src/paperless/media
      subPath: documents/paperless
    - name: media
      mountPath: /usr/src/paperless/export
      subPath: documents/export
    - name: media
      mountPath: /usr/src/paperless/consume
      subPath: documents/import
  env:
    PAPERLESS_REDIS: "redis://localhost:6379"
    PAPERLESS_DBHOST: "localhost"
    PAPERLESS_TIKA_ENABLED: "1"
    PAPERLESS_TIKA_GOTENBERG_ENDPOINT: "http://gotenberg:3000"
    PAPERLESS_TIKA_ENDPOINT: "http://localhost:9998"
    PAPERLESS_CONSUMER_POLLING: "20"
    PAPERLESS_FILENAME_FORMAT: "{title}"
    PAPERLESS_FORCE_SCRIPT_NAME: "/paperless"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

hostnames: []

storage:
  configClaimName: config-pvc
  mediaClaimName: media-pvc

gatewayClassName: traefik
