service:
  name: lidarr
  image: "lscr.io/linuxserver/lidarr:latest"
  replicas: 1
  servicePort: 8686
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1024Mi
  livenessProbe:
  readinessProbe:
  httpRoutePath: "/lidarr"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: lidarr
    - name: media
      mountPath: /downloads
      subPath: downloads
    - name: media
      mountPath: /media/music
      subPath: media/music
  env:

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

hostnames: []

storage:
  configClaimName: config-pvc
  mediaClaimName: media-pvc

gatewayClassName: traefik
