service:
  name: sabnzbd
  image: "lscr.io/linuxserver/sabnzbd:latest"
  replicas: 1
  servicePort: 8080
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
  livenessProbe:
  readinessProbe:
  httpRoutePath: "/"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: sabnzbd
    - name: media
      mountPath: /downloads
      subPath: downloads/sabnzbd
  env:
    PUID: "1000"
    PGID: "1000"
    TZ: "Etc/UTC"

securityContext:

hostnames:
  - sabnzbd.local

storage:
  configClaimName: config-pvc
  mediaClaimName: media-pvc

gatewayClassName: traefik
