service:
  name: bazarr
  image: "lscr.io/linuxserver/bazarr:latest"
  replicas: 1
  servicePort: 6767
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1024Mi
  livenessProbe:
  readinessProbe:
  httpRoutePath: "/bazarr"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: bazarr
    - name: media
      mountPath: /downloads
      subPath: downloads
    - name: media
      mountPath: /media/tvshows
      subPath: media/tvshows
    - name: media
      mountPath: /media/movies
      subPath: media/movies
  env:

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

hostnames: []

storage:
  configClaimName: config-pvc
  mediaClaimName: media-pvc

gatewayClassName: traefik
