service:
  name: mylar3
  image: "lscr.io/linuxserver/mylar3:latest"
  replicas: 1
  servicePort: 8090
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1024Mi
  livenessProbe:
  readinessProbe:
  httpRoutePath: "/mylar3"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: mylar3
    - name: media
      mountPath: /downloads
      subPath: downloads
    - name: media
      mountPath: /data/comics
      subPath: media/books/comics
  env:
    PUID: "1000"
    PGID: "1000"

securityContext:
  # runAsUser: 1000
  # runAsGroup: 1000
  # fsGroup: 1000

hostnames: []

storage:
  configClaimName: config-pvc
  mediaClaimName: media-pvc

gatewayClassName: traefik
