apiVersion: v1
kind: PersistentVolume
metadata:
  name: configs-pv
  labels:
    type: config
spec:
  storageClassName: {{ .Values.storage.storageClass }}
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.configsPath }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  labels:
    type: media
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass }}
  local:
    path: {{ .Values.storage.mediaStoragePath }}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
  labels:
    type: immich
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass }}
  local:
    path: {{ .Values.storage.immichStoragePath }}
