apiVersion: v2
name: shared
description: Shared chart for my entire media stack

# A chart can be either an 'application' or a 'library' chart. A library chart
# is a collection of templates that can be re-used in other charts.
type: application

version: 0.1.0

appVersion: "0.1.0"
