apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}-db
  name: {{ .Values.service.name }}-db
spec:
  replicas: {{ .Values.service.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name }}-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service.name }}-db
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.storage.configClaimName }}
      containers:
        - name: gamevault-db
          image: postgres:17
          livenessProbe:
          volumeMounts:
            {{- toYaml .Values.service.dbVolumeMounts | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.service.name }}-db-config
          env:
            {{- range .Values.service.dbEnvSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
