app:
  name: qbittorrent
  image: "linuxserver/qbittorrent:latest"
  replicas: 1

  pod:
    ports:
      servicePort: 8080
      extraPorts:
        - name: torrenting-tcp
          port: 6881
          protocol: TCP
        - name: torrenting-udp
          port: 6881
          protocol: UDP

  gateway:
    enabled: true
    httpRoutePath: "/"
    hostnames:
      - qbit.local
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: qbittorrent
    - name: media
      mountPath: /downloads
      subPath: downloads
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  environmentData:
    env:
      TORRENTING_PORT: "6881"
      WEBUI_PORT: "8080"
