app:
  name: gaseous
  image: "gaseousgames/gaseousserver:latest"
  replicas: 1

  pod:
    ports:
      servicePort: 80

  gateway:
    enabled: true
    httpRoutePath: "/"
    hostnames:
      - gaseous.local
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  volumeMounts:
    - name: media
      mountPath: /home/gaseous/.gaseous-server
      subPath: gaseous
    - name: media
      mountPath: /app/romlibrary
      subPath: games/rom-library
  environmentData:
    env:
      dbhost: "gaseous-db" # The Postgres container will run in the same pod, so we can use localhost to connect to it
      dbuser: "root" # Should match MARIADB_USER in mariadb
      TZ: "Europe/Madrid"
    envSecrets:
      - name: dbpass
        secretName: gaseous-secrets
        key: MARIADB_ROOT_PASSWORD
      - name: igdbclientid
        secretName: gaseous-secrets
        key: IGDB_CLIENT_ID
      - name: igdbclientsecret
        secretName: gaseous-secrets
        key: IGDB_CLIENT_SECRET

database:
  name: gaseous-db
  image: "mariadb:latest"
  replicas: 1

  pod:
    ports:
      servicePort: 3306

  gateway:
    enabled: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  probes:
    livenessProbe:
      exec:
        command:
          - "healthcheck.sh"
          - "--connect"
          - "--innodb_initialized"
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 5
  volumeMounts:
    - name: config
      mountPath: /var/lib/mysql
      subPath: gaseous
  environmentData:
    env:
      MARIADB_USER: "gaseous"
    envSecrets:
      - name: MARIADB_PASSWORD
        secretName: gaseous-secrets
        key: MARIADB_PASSWORD
      - name: MARIADB_ROOT_PASSWORD
        secretName: gaseous-secrets
        key: MARIADB_ROOT_PASSWORD
