app:
  name: radarr
  replicas: 1

  pod:
    image: "lscr.io/linuxserver/radarr:latest"
    ports:
      servicePort: 7878
    volumeMounts:
      - name: config
        mountPath: /config
        subPath: radarr
      - name: media
        mountPath: /downloads
        subPath: downloads
      - name: media
        mountPath: /media/movies
        subPath: media/movies
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000

  gateway:
    enabled: true
    httpRoutePath: "/radarr"
