app:
  name: retrom
  image: "ghcr.io/jmberesford/retrom-service:latest"
  replicas: 1
  servicePort: 5101
  httpRoutePath: "/"
  volumeMounts:
    - name: config
      mountPath: /app/config/
      subPath: retrom/config
    - name: config
      mountPath: /app/data/
      subPath: retrom/data
    - name: media
      mountPath: /app/romlibrary
      subPath: games/rom-library
  hostnames:
    - retrom.local
