apiVersion: v2
name: cert-manager
description: Automated TLS certificate provisioning and renewal for Ingress resources in Kubernetes

# A chart can be either an 'application' or a 'library' chart. A library chart
# is a collection of templates that can be re-used in other charts.
type: application

version: 0.1.0

appVersion: "latest"
