app:
  name: vaultwarden
  image: "vaultwarden/server:latest"
  replicas: 1
  servicePort: 80
  httpRoutePath: "/"
  volumeMounts:
    - name: config
      mountPath: /data
      subPath: vaultwarden
  hostnames:
    - "vault.local"
  secureGateway: true
