app:
  name: vaultwarden
  replicas: 1

  pod:
    image: "vaultwarden/server:latest"
    ports:
      servicePort: 80
    volumeMounts:
      - name: config
        mountPath: /data
        subPath: vaultwarden

  gateway:
    enabled: true
    httpRoutePath: "/"
    secure: true
    hostnames:
      - "vault.local"
