{{- if .Values.includeGlobs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-files
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
data:
{{- range .Values.includeGlobs }}
{{ ($.Files.Glob .).AsConfig | indent 2 }}
{{- end }}
{{- end }}
