apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.name | required "Please provide a name for the service you want to deploy" }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.storage.configClaimName }}
        - name: media
          persistentVolumeClaim:
            claimName: {{ .Values.storage.mediaClaimName }}
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.image | required "Please provide an image for the service you want to deploy" }}
          name: {{ .Values.name }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.commandArgs }}
          args:
            {{- toYaml .Values.commandArgs | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.servicePort }}
              protocol: TCP
            {{- range .Values.hostPorts }}
            - containerPort: {{ .port }}
              protocol: {{ .protocol | default "TCP" }}
              name: {{ .name }}
              hostPort: {{ .port }}
            {{- end }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-config
          env:
            {{- range .Values.envSecrets }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .key }}
            {{- end }}
