apiVersion: v2
name: filebrowser-quantum
description: A Helm chart for Kubernetes to deploy FileBrowser Quantum

# A chart can be either an 'application' or a 'library' chart. A library chart
# is a collection of templates that can be re-used in other charts.
type: application

version: 0.1.0

appVersion: "stable"

dependencies:
  - name: basechart
    version: "0.1.0"
    repository: "file://../basechart"
    alias: app
