app:
  name: prowlarr
  image: "linuxserver/prowlarr:latest"
  replicas: 1

  pod:
    ports:
      servicePort: 9696

  gateway:
    enabled: true
    httpRoutePath: "/prowlarr"
  volumeMounts:
    - name: config
      mountPath: /config
      subPath: prowlarr
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
